on: push
jobs:
  check:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        node: ['12', '14', '16']
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - uses: ./
      - env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'Hello CML from ${{ matrix.system }}!' > report.md

          vl2svg assets/vega-lite.json | cml publish --md >> report.md
          vl2png assets/vega-lite.json | cml publish --md >> report.md

          cml send-comment report.md
          cml send-github-check report.md
